#RNA seq analysis of Suzuki et al. 2017 combined salt and HS
# RNA-Seq data generated by this study was deposited in NCBI GEO repository 
# under the accession/reference number GSE72806

# Load necessary libraries
library(DESeq2)
library(edgeR)
library(readr)
library(GEOquery)
library(vsn)
library(ggplot2)
library(pheatmap)
library(formattable)
library(VennDiagram)
library(viridis)
library(dplyr)
library(stringr)

# Set working directory
setwd("~/Desktop/palanivelu_lab/small_peptide_review/R")

#load in metadata-------

# Specify the GSE ID
gse_id <- "GSE72806"

# Fetch the GEO data (expression data and metadata)
gse_data <- getGEO(gse_id, GSEMatrix = TRUE)

# Extract metadata (e.g., sample annotations)
meta_data <- pData(gse_data[[1]])

dim(meta_data)  # Check the metadata dimensions
head(meta_data)  # View first few rows of metadata

# Remove spaces in 'meta_data$title' and replace them with underscores
meta_data$title <- gsub(" ", "_", meta_data$title)

# Convert both 'meta_data$title' and 'ids' to lowercase
meta_data$title <- tolower(meta_data$title)

# Remove underscores and convert both to lowercase
meta_data$title <- tolower(gsub("_", "", meta_data$title))

# Path to your gzipped file
expression_file <- "data/GSE72806_CUFFDIFF_CONTROL_vs_HEAT_gene_exp.diff.gz"

# Read the expression data as tab-delimited (tsv) file
count_data_full <- read_tsv(expression_file)

# View data dimensions and initial rows
dim(count_data_full)
head(count_data_full)

# Set gene names as rownames
count_data <- count_data_full[,-1]  # Exclude the first column with gene names

# Convert to matrix
count_data <- as.matrix(count_data)

# Set the row names from the first column
rownames(count_data) <- count_data_full[[1]]  # Set the first column as row names

#-----------------

# Filter for late floral buds metadata
# Subset columns with "lf" in their names
lf_count_data <- count_data[, grepl("lf", colnames(count_data))]

lf_ids <- colnames(lf_count_data)

lf_group <- meta_data[which(meta_data$title == lf_ids),][['treatment:ch1']]# Modify as per your setup

lf_design <- model.matrix(~lf_group)

# Define the sample information as a data frame
lf_col_data <- data.frame(
  row.names = colnames(lf_count_data),
  condition = lf_group # Modify as per your setup
)

# Create DESeq2 dataset object
lf_dds <- DESeqDataSetFromMatrix(countData = lf_count_data, colData = lf_col_data, design = ~condition)
head(lf_dds)

# Apply DESeq’s normalization
lf_dds <- estimateSizeFactors(lf_dds)

# Inspect normalized counts (optional)
lf_norm_counts <- counts(lf_dds, normalized = TRUE)
formattable(head(lf_norm_counts))

# Run the DESeq2 pipeline
lf_dds <- DESeq(lf_dds)

# Extract results for all genes with default settings
lf_res <- results(lf_dds)

# Order by adjusted p-value
lf_res <- lf_res[order(lf_res$padj),]

#get meaning of the columns
mcols(lf_res, use.names = TRUE)

#other summary
summary(lf_res)

# Filter for significant results (adjusted p-value < 0.05)
lf_deseq2_genes <- subset(lf_res, padj < 0.05)

# Save to file
write.csv(as.data.frame(lf_deseq2_genes), file="output/HS_DESeq2_late_floral_results.csv")

## 1. Venn Diagram

###################################---------------------------cle_gene_list <- 

significant_genes <- list(
  DESeq2 = rownames(lf_deseq2_genes))

# Create the Venn diagram
grid.newpage()

venn.plot <- venn.diagram(
  x = significant_genes,
  category.names = c("DESeq2"),
  filename = NULL,  # Set to NULL to plot directly
  output = TRUE,
  fill = c("cornflowerblue"),
  alpha = 0.5,
  cex = 1.5,
  fontface = "bold",
  fontfamily = "sans"
)

# Display the Venn plot
grid.draw(venn.plot)

# Example Data: Assume 'results' is a data frame containing columns logFC, P.Value (or PValue in edgeR), and adj.P.Val (or FDR)
# Add a column to categorize genes as upregulated, downregulated, or non-significant
results <- as.data.frame(lf_res)
results <- results %>%
  mutate(Significance = case_when(
    padj < 0.05 & log2FoldChange > 1 ~ "Upregulated",
    padj < 0.05 & log2FoldChange < -1 ~ "Downregulated",
    TRUE ~ "Non-significant"
  ))

# Volcano Plot
ggplot(results, aes(x = log2FoldChange, y = -log10(pvalue), color = Significance)) +
  geom_point(alpha = 0.6, size = 1.5) +
  scale_color_manual(values = c("blue", "grey", "red")) +
  labs(title = "Volcano Plot of Differentially Expressed Genes",
       x = "Log2 Fold Change",
       y = "-log10(P-Value)") +
  theme_minimal() +
  theme(legend.position = "top")

# Prepare Data: Select top 50 differentially expressed genes
results <- results %>%
  mutate(gene = rownames(results)) # Add gene names if rownames exist

top_genes <- results %>%
  filter(padj < 0.05) %>%                     # Filter significant genes
  arrange(desc(abs(log2FoldChange))) %>%      # Sort by absolute log2 fold change
  slice_head(n = 40) %>%                      # Select top 50 genes
  pull(gene)                                  # Extract gene names

#CLE gene family list
cle_family <- c("AT2G27250", "AT1G73165", "AT4G18510", "AT1G06225", "AT2G31081", "AT2G31083", "AT2G31085", "AT2G31082", 
                "AT1G67775", "AT1G26600", "AT1G69320", "AT1G49005", "AT1G68795", "AT1G73965", "AT1G63245", "AT2G01505", 
                "AT1G70895", "AT1G66145", "AT3G24225", "AT1G05065", "AT5G64800", "AT5G12235", "AT3G28455", "AT1G69970", 
                "AT3G25905", "AT5G12990", "AT3G24770", "AT2G34925", "AT1G25425", "AT4G13195", "AT1G69588")

ralf_family <- c(
  "AT1G02900", "AT1G23145", "AT1G23147", "AT1G28270", "AT1G35467", 
  "AT1G60625", "AT1G60815", "AT1G61563", "AT1G61566", "AT2G19020", 
  "AT2G19045", "AT2G20660", "AT2G22055", "AT2G32835", "AT2G32885", 
  "AT2G33130", "AT2G33775", "AT2G34825", "AT3G04735", "AT3G05490", 
  "AT3G16570", "AT3G23805", "AT3G25165", "AT3G25170", "AT3G29780", 
  "AT4G11510", "AT4G11653", "AT4G13075", "AT4G13950", "AT4G14010", 
  "AT4G15800", "AT5G67070", "AT1G60913", "AT2G32785"
)


# Filter DESeq2 results
cle_filtered_genes <- results %>%
  filter(gene %in% cle_family, padj < 0.05) %>%             # Filter for genes in the CLE family with padj < 0.05
  arrange(desc(abs(log2FoldChange)))                         # Arrange by absolute log2FoldChange

ralf_filtered_genes <- results %>%
  filter(gene %in% ralf_family, padj < 0.05) %>%             # Filter for genes in the CLE family with padj < 0.05
  arrange(desc(abs(log2FoldChange)))                         # Arrange by absolute log2FoldChange

# Expression Matrix Preparation
# Assuming 'dds' is the DESeq2 object and you have a normalized counts matrix
norm_counts <- counts(lf_dds, normalized = TRUE) # Get normalized counts
heatmap_data <- norm_counts[top_genes, ]      # Subset normalized counts by top genes

# Log Transform for Better Visualization
heatmap_data <- log2(heatmap_data + 1)        # Add pseudocount and log-transform

# Group Metadata
sample_groups <- as.data.frame(colData(lf_dds)[, "condition", drop = FALSE])
colnames(sample_groups) <- "Group" # Rename for clarity
rownames(sample_groups) <- colnames(heatmap_data)

# Custom Colors for Groups
group_colors <- list(Group = c("control" = "cyan", "treated at 37C for 3h" = "magenta"))

# Heatmap Visualization
pheatmap(heatmap_data,
         color = viridis(40),
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         scale = "row",                      # Normalize rows (genes)
         show_rownames = TRUE,               # Show gene names
         show_colnames = TRUE,               # Show sample names
         annotation_col = sample_groups,     # Add group annotations
         annotation_colors = group_colors,   # Define group colors
         main = "Heatmap of Top Differentially Expressed Genes",
         fontsize_row = 7,                   # Adjust row font size
         fontsize_col = 7,                   # Adjust column font size
         angle_col = 45,
         fontsize = 8,
         #cellwidth = 20,                     # Width of each cell
         cellheight = 6) 

